// Dynamic step titles and descriptions - all generated by AI based on domain and user input

export interface StepInfo {
	title: string;
	description: string;
}

export function getDomainSpecificStepInfo(
	stepId: string,
	domain: string,
	brandName?: string,
	brandDescription?: string,
	selectedMood?: string,
	selectedAudience?: string
): StepInfo {
	// AI will generate step titles and descriptions dynamically
	// No hardcoded titles - everything is generated by AI based on user input

	return {
		title: 'AI Generated Step',
		description: 'AI will generate title and description based on your input'
	};
}

// All hardcoded functions removed - everything is now dynamically generated by AI
